### ISSUE TITLE
Forms Intro docs are kind of confusing

### ISSUE THREAD

**Issue by gilest** [universal-ember/ember-primitives#165]
The [Intro](https://ember-primitives.pages.dev/7-forms/1-intro) page seems to explore form management concepts while also documenting the `Form` component.

It's not clear from this page what is provided by `ember-primitives` and what is general discussion around form management in Ember and other ecosystem packages (ref: ember-template-lint/ember-template-lint/pull/2990)

Suggestions:

- Create a new page called `Concepts` or something similar exploring light/controlled and the different implementations of them including those in different packages like `ember-headless-form`
- Create a separate page for the `Form` component explicitly documenting it only

**Comment by NullVoxPopuli** [comment]
Thoughts on these new docs? 

https://b6ccc0df.ember-primitives.pages.dev/3-components/form

**Comment by gilest** [comment]
Much better 💯
