### ISSUE TITLE
OTP second time you paste it happens in the next input

### ISSUE THREAD

**Issue by evoactivity** [universal-ember/ember-primitives#228]
In the video I paste, and then paste again when in the first input, but the second paste happens in the next input

https://github.com/universal-ember/ember-primitives/assets/83799/ed2b954d-b226-45ed-ac62-df75ccce77b5

**Comment by NullVoxPopuli** [comment]
Thanks for reporting!

Fixed in 0.11.0

https://github.com/universal-ember/ember-primitives/releases/tag/v0.11.0-ember-primitives
