### ISSUE TITLE
OTP clicking into input stops auto advance working

### ISSUE THREAD

**Issue by evoactivity** [universal-ember/ember-primitives#229]
I would expect it to replace the character in the input I click into and go from there.

https://github.com/universal-ember/ember-primitives/assets/83799/14dd0b79-ac60-486b-9ed9-59bbcde86555

**Comment by NullVoxPopuli** [comment]
I would agree!

**Comment by evoactivity** [comment]
This happens if using arrow keys too, not just clicking.

**Comment by NullVoxPopuli** [comment]
yeah, this should be a very easy thing to test for, I just have some repo mainenance to get through first :sweat_smile: (been slacking on deps)

**Comment by NullVoxPopuli** [comment]
Thanks for reporting!

Fixed in 0.11.0

https://github.com/universal-ember/ember-primitives/releases/tag/v0.11.0-ember-primitives
