### ISSUE TITLE
OTP backspace without typing again doesn't run onChange

### ISSUE THREAD

**Issue by evoactivity** [universal-ember/ember-primitives#247]
New version has a new bug :) 
Previously hitting backspace would run the onChange handler, now it doesn't.

**Comment by NullVoxPopuli** [comment]
Curses! I really wish backspace was a testable keypress!

**Comment by NullVoxPopuli** [comment]
Released in 0.11.1!

https://github.com/universal-ember/ember-primitives/releases/tag/v0.11.1-ember-primitives
