### ISSUE TITLE
Manually entering URL for "Form" does not load correct page

### ISSUE THREAD

**Issue by barryofguilder** [universal-ember/ember-primitives#302]
I had copied the URL for the form component to my notes. When I click the link to go directly to the form page, it doesn't load the correct page.

![Screenshot 2024-04-30 at 10 13 36 AM](https://github.com/universal-ember/ember-primitives/assets/5649106/f5ebd146-e0e1-455b-bc6e-efd0675402a7)

If I click on the "Form" menu item on the side, then it loads the correct page. If I click the refresh button on the form page, it also works. I'm not sure why going to it by clicking on a link (not in the browser) causes it to not load the page.

**Comment by NullVoxPopuli** [comment]
that URL changed to https://ember-primitives.pages.dev/3-ui/form

thanks for reporting! this changed quite recently
