### ISSUE TITLE
Body scroll lock on Modal component

### ISSUE THREAD

**Issue by amk221** [universal-ember/ember-primitives#53]
Currently, the ember-primitives [Modal demo](https://ember-primitives.pages.dev/3-components/modal) prevents scrolling of the content _behind_ the open modal dialog. 

But if one creates a modal dialog, using minimal code such as that [provided by MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#simple_example), like [this one](https://limber.glimdown.com/edit?c=AYjmCsGcAIBsEsBuBTAUPAtgBwPYCcAXaAb2hwDtoBfaAMzxw2gHIABZDAI2TwHoMcAE3i14PZgG5UqAMYVIRHFmTkAskICGsaAF5oACmQpyBAJS6AfCVTRognDICuGFQQB0AR0c8AngGVkWGQZAnx9ZgBiYS0cUGZTN0gACxwAd3VBLX1TKSppAB4CDixYDSKLG2h8zkcCUMoCH2UdACIauooW6HhBVvb6ruJiCmgWmQQZAGsupRUMrSoqCtsAeWVKAUztaNhY1HzefooK-Z3Y7t6Ws9AW5egACUDd6AB1fFhBfd5rk5f7gE1oABVaAAORW0AAQisACKAvwAYQASisADKo6ColYIgDS0AA-Jj8BxulhIM47DhdnhoJB4EQNC4CAAaaByciQYJFAiOGkaYRYeCQGTwcigaCBeluaAARUcQq8yAljmgPLwgpgyFAyCITMcMC08C8jLoeFFoHgsFKF1pyEE0HIjitGml6jwnHgytp%2BpFgqIZvJkFZiHpGiVuEIGmgGA0vKF0oC9pQ2gIopFgkcJkp1IT%2BvWwkgnIltFEIrV0apCE1CBZ0DKEqCIhU9qwvP1tM0QQN7mgqljAbgjhC7dChHw3Uo4H1oWgeBS5CcQegXiFbMYmxwDszMmgrdgIfIGjwrrDMhUGhgyYlAA9oCGCGHaRpBSpuhonFXVcV9dLQduO1a8Blo4wiULQkowKUi6sqKu5PK4yCQIqW4LrOtR4BStRuNIACSJhajwDYcK4zisvY1J3qGSoEQoF60meQQBoqrI8DgMAxoWUaIEe8DtkeTgsSqMZ1KujqoaOo62va5BCrA0qosSTDwGSFLkeOdIMkyrLspyIQ6rydYCkKIpig2Upgia5DBKS5JMFZirSgACvB%2BFId4dDvpaQqrvQ5qWtagTESYzjSnKCruaUxI6rubYGnekpEJgyh4MI0VOgQZpnpA0oAKKpia7LCC4wVMJydnWTGoCHtA6WZWIS7kCMsYhOOak0oFTbkIITkMLBOnIMauoXpAUaFZgJFMHOFCLoOw7ZdAMLyjAY3FTyTDKFaCFuUqjrOpRD7hlBPBlCewTngajigO5Ab6ixjbgV1dbxQo8A1LAFKNeQLElkB9IGZ98U1k5LlFNtdA8KtFL4CKdaKHgMNFNg%2BAwZQiBUrUWD1mVz2pm9IVgk6pRMLVQGIaafl7axl6BNGWiIY4-IugTe2iDJNSQVy7YA21a5deNJWCaqaY9JmRBBJu71zdKCJ4HR-V6eWrOve20PwNKMIUNZ7LcYBF1XUqbWC5Ala-TyoGqryGpsrygb7WGv6E1xPHtohRBYEkR46rLQsLiLWbNaO2GoM5m2uch7uexlUYB%2BOKiYNKABqrvK%2B9xN4NVN1Lv1g2USgeDe6rgOsjGXYM5k0AetwXUUlOCg4LmkD5kKRaSzyMCZ3WO6uz76ai8GVFEZ19ocSN4OXfAJ3QHhRTajSGaenqS5JM2eA8PSgMdlsZNWTIrJQaKE9SXAiknnGy3rkIm7Gkw74Sgw58cgNDNECNFoifNf6oYgTqtg%2BRRkVSWO2oxZDjbruNi3hV6sjZkkaM%2BkYC0E8lWVcccMAwSTCoc8qZ2KehGi%2BVGmDDzYLvmxBMdo4AaCimLTmmoGT4QrLrTuTgMAjXIEHBEvINAenLMgW8hsKEmUPj0NCGUKSij3qA9sV5ogYGlpw7hBl94ySjLta0I8NCsijElHgqUiAwO9MKZS68UBJCAk6Jmf49oCEYcmdevJDyaPiqYj8UZF68x1p%2BZMDsv5IB4N7VMvsMxZlbBhJcsEaIPk1LLF%2BJtgLmwsY7XOfiVH-gBrGfWEptS0QQWaMU-kmaOQ9pyK07YYzXkwFI5AzjzG0yqhozJ0VK7NgpAgK61pMiCnZrSdejIdSunwB6XcHtV5RwdK9WBBEiDHSIOyDJoBZYhkyNKIEL8GJrzBh3cCVZWS1EHg9e00y6AHy6V4gmqFhFCHgJuWCbinB4Fth05W81CkXieC7YBFdSh8z0bJROyc8ZMCvMJYhWz4zMyJhvVpNTHYYDkOqHgrIAm9yzEUEpBpd5kHTp7MZkA5KyiWshRGEY6yXXchPD8KCZJMHmRoRZ9TkAqhDHnb2tjVmBSYt4aU08dEUmiiXemjMPIuHRXWehylbK7jNBgVcsFEFDieU5IpbyH66W5AZJp1cmAxjPg0mZF97Dq01juDKQpUzMSfPgzuX4kY0m0SlMQtZQUwEuZuOQGANx2HlKyRBIpkEwGNlvdi-ZVzaoHBpOsTI4DIHrtIDWO8e5%2BymVkyJgNjED2Xl1VeZoeyWIhWqK2TrWR7gPEeI%2B0qJyshpXShhn4oWlB6mGTkWZ%2BXkkFQlJ6dzbYZsEFm8yScXoAuXEtI5bMVbCHrtAAAggga%2BQ6TT8UcEW-AIlJL1lwOSHgO1gislfvSYhDLoxqynvhWea53WXzPR6qtPQEl7VnTA4M-ynS8piYBOJ4TgGCSFJsJ66jpSTswRoDYJsYAhK5tZH1Xk6TViCmtaU0hbAKVXkpFSTAebht6bWeWaq%2BRGUMaZBKoUCXuQPfmlBHy3GGlnb5PJe1hGcmko7fp7pPQHsDL6demd%2B4HXAZGWmZ8yEYJTMLIJRA2oNyboWaiP1gI0msZ%2BBKmipn3WbDFUJm86bdlPgOVuI5l3jlgrXGcU0Fy3SHauN1HqxI7mLaKI8p0zyHmptoXhdslR4LEJQclTpVxEp-Gcncxs31-XNk6gRZnYIbSCGHdy1mREYWJu4XCJ7CKBUhmg7M457yPgiXRYU7LwrIBYvfWmnE7zOwNPDRdXpgWiX-BJdS5CZK4vkopGyqlAE0gw1pXmqr9K4aMfh8UhGLLlR3OKj6T9kDA1DqDZCkG-Xk1owFII6WiOFYoVQtTfFU2JWwDoh1NVYAmqyrlfKTAVoTVtGN2p1USYikQtApqoDWqdb2c2HqOA%2BryCfvWdRvMipXZMzNXT81FoWYoIDkqcFZuIWQqoriA8SjvmmQ586JKMlcfe49LiT7U4OgoN9Usf0aQA1ZTN6Lc33LgTwOlzFMN6yFyJcjCcd50YEExi-EkKAB3PtkeCk092yY0YtJTErQLNNl1vdaJWXSghzQJ5QHml2BZeiRYmqNEtJHzRlnLH7CsDKy5VvDI9catYUA8audJ7l%2BFsdiSF2CZHlo2ykVRB2e1uJmhdgoIZkd-EidFiSlqx5pAh0p3D9yEcRnexju1Klfzef4-sVGLH2dn5JPzlGQuyZi6S8FRqjMTAjMTr8HmZszclSg9nEKPiXcffq9E9xnLKnHr-fAuPSe3LT3zzgW3Vk3be1ECvAGzTDpt0CIPlGBjx9kPaYh%2Be%2Bwc6b5dxK2nrGGg37YO8Tub%2BsBf5lCK5l9qHyq-rsgYf-RbiFveU1FS9B8UrJEJDbg58nmH9YJQffQTm3V7RXl2A6KIDIoGtK3GQZhVhdheREnG8I-PeTyZRG0DCURJSL6WaMBaRCefnDhWWBRGkJRQ%2BBHUrEaRxO1XRMZTgWBdjIxIfKpMxetAXEA5zOxLFRxExOg1xeBdxLQTxQIbfDPf3QJQPMDMJSgXLKJLGe3M2WCaXRHZlFJVCNJUlaiZNOiEXfJRVV5NFWmcpDASpapNRDfBxXVCuV6ZpJgOtKMR5LpbrPpXsAZT0KPL2FRcZYww5WZdya9JZYENlRiDbTZCCHZZTZAIeO%2BesI3ZzPgi5cdVnW5F3GAKw-zF5Ypd6TUD5TgL5YQH5FraAftXGPnDeWrBBCCd3CFK8Cwo7ImOFZKRFAPFFZVTuVkfAQ8VeHFPFMKMGZnPkJQt8ClW-TAaATw%2BlRlXxTPXbeiArbaLlfCFKF9WmUuQVRBYVK1IApUCbdaKVGVMCZqBVaAJI%2Bo7DfrEwquQvfjAcSZS9S%2BQ1eNE1F6c1DzV8W%2BTo7ofbe1HUb1CCMgaIyzC9eeb1JBG-DTLsU4kNYNf1HpSNcWIOM3Y1WopNV2OiVlNzaAAfNeHNGFC2dUHyAImKfcOzLrchctcRAYhZG9RguAeANpApWWRCVwOYgVcudtUaOI5EleVEhPPI-HFcBBY5MdK5f9GdBmJgWdBdJdQgVMVdN2CBTdMfDFXdd%2BGrI9LvQib4xfFUzcQYkoqMe9cZR9RPWYoLCYB3UQz9ZUb9IQX9YaJmADKyIDMk4QmUjyX1AEtLCaeDA4IlUocoVAEAYAVAIAA&format=glimdown), you'll notice that there is no body scroll lock behaviour!

This issue is for tracking why the ember-primitives version behaves the way it does and to get some clarification about when body scroll locking kicks in (if at all - since it's not mentioned in the MDN docs)

**Comment by NullVoxPopuli** [comment]
For Modals, I think the behavior of not scrolling the background is correct, because not-locking it is confusing, as you can't actually focus anything in the background anyway.

As to why the demo, https://ember-primitives.pages.dev/5-floaty-bits/modal, locks body scroll, I don't actually know how that's happening.

There is of course, a different kind of popup that is more like a window in your OS, allowing resizing, dragging, and interacting with background content -- this isn't a common pattern in modern webdev, but could still be implemented. It's a bit of an a11y nightmare, and maybe impossible to correctly handle ergonomically for folks without mice _and_ eyes as their primary I/O with an app.
